name: CI

on:
  issue_comment:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: NPM Install
        run: npm install
      - name: Run tests
        run: npm test
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v1.1
        if: always()
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/upload-artifact@v1
        if: always()
        with:
          name: sonar_results
          path: sonar_results
        # inputs:
        #   configMode: "file"
        #   # This sonar-project.properties file is usually placed at the root level of the repository. However, you can define your own path.
        #   # Read more about this file and its expected format : https://docs.sonarqube.org/latest/analysis/scan/sonarscanner/
        #   configFile: "sonar-project.properties"
