name: CI

on: [issue_comment]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: NPM Install
      run: npm install
    - name: Run tests
      run: npm test
